Worksheet 5


This worksheet covers L13. Use numpy array syntax only; do not use for loops.

In [1]:
# 1. Using the function arange, create an array of 10 integers 'd' from -20 to 25 (inclusive), in steps of 5.
import numpy as np
d = np.arange(start=-20, stop=26, step=5)

In [2]:
# 2. Multiply all values in d by 10, storing the result in d2.
d2 = d*10

In [3]:
# 3. Add the values stored in d and d2, element-wise, printing the result to the console
print(d+d2)

[-220 -165 -110  -55    0   55  110  165  220  275]


In [4]:
# 4. Resize (not reshape) d2 into a 5x2 array.
d2.resize(5,2)

In [5]:
# 5. Create an array d3, containing the integers 1,2,3,4,5.
d3 = np.array([1,2,3,4,5])

In [6]:
# 6. Reshape d3 into the necessary shape such that d2*d3 succeeds (hint: broadcasting). 
# Save the result of d2*d3 into d4 and print d4 to the console.
d3 = np.reshape(d3,(5,1))
d4 = d2*d3
print(d4)

[[-200 -150]
 [-200 -100]
 [   0  150]
 [ 400  600]
 [1000 1250]]


In [7]:
# 7. In a single line of code, print to the console the 1st, 3rd and 5th rows, both columns, of d4.
print(d4[[0,2,4],:]) 

[[-200 -150]
 [   0  150]
 [1000 1250]]


In [8]:
# 8. Create a deep copy of d4, storing in d5. 
# Print a comparison of d4 and d5 object IDs to show the two are not equal.
d5 = d4.copy()
print(f"d4 id: {id(d4)} = d5 id: {id(d5)}?\t{id(d4) == id(d5)}")

d4 id: 2941428326320 = d5 id: 2941428327088?	False


In [9]:
# 9. Resize (not reshape) d4 into a 2x5 array.
d4.resize(2,5)

In [10]:
# 10. Flatten (not reshape) d4 back into a 10x1 array. 
# Print the result to the console. Your output should match: [-200 -150 -200 -100 0 150 400 600 1000 1250]. 
# Next, print d5 to the console. The shapes of the two arrays should be different
d4 = d4.flatten()
print(d4,"\n__________\n")
print(d5)

[-200 -150 -200 -100    0  150  400  600 1000 1250] 
__________

[[-200 -150]
 [-200 -100]
 [   0  150]
 [ 400  600]
 [1000 1250]]
