### NumPy arrays

**1. Array programming**

In [29]:
import numpy as np

In [6]:
# Initialise
nums = np.array([2,4,6,8,9])
# Check type
print(type(nums))
# Evaluate
#nums
print(nums)

<class 'numpy.ndarray'>
[2 4 6 8 9]


In [7]:
print(nums)
# Vectorised multiplication
print(nums*5)
print(nums)
# Element-wise addition
nums2 = np.array([10, 20, 30, 40, 50])
print(nums + nums2)
# Raise to power 2
print(nums**2)

[2 4 6 8 9]
[10 20 30 40 45]
[2 4 6 8 9]
[12 24 36 48 59]
[ 4 16 36 64 81]


In [30]:
nums2 = np.array([2, 4, 'foobar'])

In [31]:
print(nums2)

['2' '4' 'foobar']


**Comparing lists with arrays**

In [34]:
import time
# Generate list of 10,000,000 random numbers
array1 = np.random.randn(10**3)
array2 = np.random.randn(10**3)
# Copy into list
list1 = list(array1)
list2 = list(array2)
# 10,000,000x1 vector
print(array1.shape)

# List dot product
dot = 0
initialTime = time.time()
for a, b in zip(list1, list2):
        dot = dot + (a * b)
print("List dot product: ", round(time.time() - initialTime, 5), " seconds")

# Array dot product
initialTime = time.time()
array = np.dot(array1, array2)
print("Array dot product: ", round(time.time() - initialTime, 5), " seconds")

(1000,)
List dot product:  0.00046  seconds
Array dot product:  0.0001  seconds


**3. Array attributes** 

In [36]:
# 2x3 array
d = np.array([[1,2,3], [4,5,6]])
print(d)

[[1 2 3]
 [4 5 6]]


In [39]:
# Data type within array
print(d.dtype)
# Array of floats
f_array = np.array([0.0, 0.1, 0.2, 0.9])
print(f_array)
f_array.dtype

int64
[0.  0.1 0.2 0.9]


dtype('float64')

In [37]:
print(d)

[[1 2 3]
 [4 5 6]]


In [38]:
# 2D Int array
print(f"2D array: \n{d}")
print(f"Dims: {d.ndim}")
print(f"Shape: {d.shape}")
print(f"Num elements: {d.size}")

2D array: 
[[1 2 3]
 [4 5 6]]
Dims: 2
Shape: (2, 3)
Num elements: 6


In [40]:
# 1D float array
print(f"1D float: \n{f_array}")
print(f"Dims: {f_array.ndim}")
print(f"Shape: {f_array.shape}")
print(f"Num elements: : {f_array.size}")

1D float: 
[0.  0.1 0.2 0.9]
Dims: 1
Shape: (4,)
Num elements: : 4


**Iterating with arrays**

In [43]:
print(d,"\n----\n")
for row in d:
    for column in row:
        print(column, end=' ')
    print()

[[1 2 3]
 [4 5 6]] 
----

1 2 3 
4 5 6 


In [12]:
# Flatten array
for element in d.flat:
    print(element, end = ' ')

1 2 3 4 5 6 

In [13]:
# Print first 4 elements of flattened array
print(d.flat[0:4])

[1 2 3 4]


**4. Filling and creating**

In [13]:
# 5x1 array of zeros
d = np.zeros(5)
print(d)

[0. 0. 0. 0. 0.]


In [14]:
# 3x2 array containing -99
d = np.full((3,2), -99)
print(d)

[[-99 -99]
 [-99 -99]
 [-99 -99]]


In [15]:
# Creating with range functions
np.arange(start=1, stop=20, step=3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [16]:
# Ten linearly-spaced floats
np.linspace(start=1, stop=99, num=10)

array([ 1.        , 11.88888889, 22.77777778, 33.66666667, 44.55555556,
       55.44444444, 66.33333333, 77.22222222, 88.11111111, 99.        ])

In [49]:
# Initialise and reshape our array
print(np.linspace(start=1, stop=100, num=12).reshape((3,4), order='f'))
# Fortran-like index ordering (first index changing fastest)
print(np.linspace(start=1, stop=100, num=24).reshape((3,2,4), order='c'))

[[  1.  28.  55.  82.]
 [ 10.  37.  64.  91.]
 [ 19.  46.  73. 100.]]
[[[  1.           5.30434783   9.60869565  13.91304348]
  [ 18.2173913   22.52173913  26.82608696  31.13043478]]

 [[ 35.43478261  39.73913043  44.04347826  48.34782609]
  [ 52.65217391  56.95652174  61.26086957  65.56521739]]

 [[ 69.86956522  74.17391304  78.47826087  82.7826087 ]
  [ 87.08695652  91.39130435  95.69565217 100.        ]]]


In [51]:
# Concise printing
print(np.arange(start=1, stop=100001).reshape(4, 25000))
print(np.arange(start=1, stop=100001).reshape(25000, 4))

[[     1      2      3 ...  24998  24999  25000]
 [ 25001  25002  25003 ...  49998  49999  50000]
 [ 50001  50002  50003 ...  74998  74999  75000]
 [ 75001  75002  75003 ...  99998  99999 100000]]
[[     1      2      3      4]
 [     5      6      7      8]
 [     9     10     11     12]
 ...
 [ 99989  99990  99991  99992]
 [ 99993  99994  99995  99996]
 [ 99997  99998  99999 100000]]


**5. Operators and Calculations**

In [52]:
nums = np.arange(1, 6)

In [53]:
print(f"Array: {nums}")
print(f"Array*2: {nums*2}")
print(f"Array^3: {nums ** 3}")
print(f"Array: {nums}")


Array: [1 2 3 4 5]
Array*2: [ 2  4  6  8 10]
Array^3: [  1   8  27  64 125]
Array: [1 2 3 4 5]


In [54]:
# Simple broadcasting
a = np.arange(0,5)
b = 5
print(a*b)

[ 0  5 10 15 20]


In [ ]:
d1 = np.arange(0,27).reshape(3,3,3)
d2 = np.array([1,2,3])
print(f"d1 shape: {d1.shape}\nd2 shape: {d2.shape}")
print(d1)
print(d1*d2)

In [23]:
# Element-wise multiplication
d1 = np.linspace(0,10,num=5)
d2 = np.array([1,2,3,4,5])
print(d1 * d2)

[ 0.  5. 15. 30. 50.]


In [59]:
# Four students each with 3 exam grades
grades = np.array([[75, 59, 60], [100, 85, 92],
                   [55, 78, 93], [14, 88, 65]])
print(grades)
grades.shape

[[ 75  59  60]
 [100  85  92]
 [ 55  78  93]
 [ 14  88  65]]


array([[150, 118, 120],
       [200, 170, 184],
       [110, 156, 186],
       [ 28, 176, 130]])

In [25]:
# Calculations
print(f"Mean: {grades.mean()}")
print(f"Sum: {grades.sum()}")
print(f"Max: {grades.max()}")
print(f"Std: {round(grades.std(),2)}")

Mean: 72.0
Sum: 864
Max: 100
Std: 22.56


In [26]:
# Calculate average exam grade (column)
print(f"Mean exam: {grades.mean(axis = 0)}")

# Calculate students' average grades
print(f"Mean grade: {grades.mean(axis = 1)}")

Mean exam: [61.  77.5 77.5]
Mean grade: [64.66666667 92.33333333 75.33333333 55.66666667]
