## L23- Review

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Strings

In [13]:
type('hello')

str

In [ ]:
print("Another","question",sep=" ",end="?")

In [16]:
s = "Peter, Paul, and Mary"
print(s[0:8])

Peter, P


In [ ]:
fruit = 'another question'
print(fruit[::3])

In [17]:
# For loop
prefixes = "JKLMNOPQ" 
suffix = "ack"
for letter in prefixes: 
    print(letter + suffix)

Jack
Kack
Lack
Mack
Nack
Oack
Pack
Qack


### Lists

In [18]:
# Initialise list
elements = ["Apple", 4, 4.3234, False, False]
print(elements)

['Apple', 4, 4.3234, False, False]


In [19]:
fruits = ['apple', 'pear', 'peach', 'banana', 'watermelon', 'strawberries']
last_fruit = fruits.pop()
print(f"The last fruit I ate was {last_fruit.upper()}")
print(fruits)

The last fruit I ate was STRAWBERRIES
['apple', 'pear', 'peach', 'banana', 'watermelon']


### Dictionaries


In [20]:
# Initialise
person = {'name' : 'Fred', 'age' : 32, 'is_single' : True}
print(person)
print(person['age'])

{'name': 'Fred', 'age': 32, 'is_single': True}
32


### Numpy arrays

In [34]:
nums = np.array([2,4,6,8,9])
print(nums[0:3] * 9)
# 4 * 2
print(nums[0:4] * nums[4])
type(nums.dtype)

[18 36 54]
[18 36 54 72]


numpy.dtypes.Int64DType

In [6]:
nums = np.array([2,4,6,8,9])
# Check type
print(type(nums))
# Element-wise addition
print(nums + nums)
# Raise to power 2
print(nums**2)
# Data type within array
print(nums.dtype)

<class 'numpy.ndarray'>
[ 4  8 12 16 18]
[ 4 16 36 64 81]
int64


In [35]:
# 2x3 array
d = np.array([[1,2,3], [4,5,6]])
print(d)
# 2D Int array
print(f"2D array: \n{d}")
print(f"Dims: {d.ndim}")
print(f"Shape: {d.shape}")
print(f"Num elements: {d.size}")

[[1 2 3]
 [4 5 6]]
2D array: 
[[1 2 3]
 [4 5 6]]
Dims: 2
Shape: (2, 3)
Num elements: 6


In [36]:
# Creating with range functions
np.arange(start=1, stop=20, step=3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [37]:
# Ten linearly-spaced floats
np.linspace(start=1, stop=99, num=10)

array([ 1.        , 11.88888889, 22.77777778, 33.66666667, 44.55555556,
       55.44444444, 66.33333333, 77.22222222, 88.11111111, 99.        ])

In [ ]:
# Simple broadcasting
a = np.arange(0,5)
b = 5
print(a*b)

In [40]:
# Four students each with 3 exam grades
grades = np.array([[75, 59, 60], [100, 85, 92],
                   [55, 78, 93], [14, 88, 65]])
print(grades)
#grades.shape
grades[[1,3], :]

[[ 75  59  60]
 [100  85  92]
 [ 55  78  93]
 [ 14  88  65]]


array([[100,  85,  92],
       [ 14,  88,  65]])

In [41]:
# Calculations
print(f"Mean: {grades.mean()}")
print(f"Sum: {grades.sum()}")
print(f"Max: {grades.max()}")
print(f"Std: {round(grades.std(),2)}")

Mean: 72.0
Sum: 864
Max: 100
Std: 22.56


In [ ]:
print(grades,"\n-----")
# Select row 1
print(grades[1,:])
# Select rows 0 and 1
print(grades[0:2,1])
# Select all rows in column 1
print(grades[:,1])

### Pandas

In [42]:
# Series
d = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
d

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
# Data as dictionary
data = {"province": ["Ontario", "Ontario", "Ontario", "Alberta", "Alberta", "Alberta"],
"year": [2010, 2011, 2012, 2011, 2012, 2013],
"pop": [13.1, 12.9, 14.6, 3.6, 4.3, 4.0]}
frame = pd.DataFrame(data)
frame

province  year   pop
0  Ontario  2010  13.1
1  Ontario  2011  12.9
2  Ontario  2012  14.6
3  Alberta  2011   3.6
4  Alberta  2012   4.3
5  Alberta  2013   4.0

In [43]:
# Reindex
print(d)
d2 = d.reindex(["e","a","b","c","d"])
d2

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64


e    NaN
a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [4]:
# loc and iloc
provinces = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=["Ontario", "Quebec", "Alberta", "British Columbia"],
columns=["one", "two", "three", "four"])
provinces

one  two  three  four
Ontario             0    1      2     3
Quebec              4    5      6     7
Alberta             8    9     10    11
British Columbia   12   13     14    15

In [5]:
print(provinces,"\n-----")
# Label-based
print(provinces.loc[["Ontario","Alberta"]])

                  one  two  three  four
Ontario             0    1      2     3
Quebec              4    5      6     7
Alberta             8    9     10    11
British Columbia   12   13     14    15 
-----
         one  two  three  four
Ontario    0    1      2     3
Alberta    8    9     10    11


In [6]:
print(provinces,"\n----")
# Integer-based
print(provinces.iloc[[0,2]])
print(provinces.loc[["Ontario","Alberta"]])

                  one  two  three  four
Ontario             0    1      2     3
Quebec              4    5      6     7
Alberta             8    9     10    11
British Columbia   12   13     14    15 
----
         one  two  three  four
Ontario    0    1      2     3
Alberta    8    9     10    11
         one  two  three  four
Ontario    0    1      2     3
Alberta    8    9     10    11
