In [1]:
# Generate a 5x5 array with random values between 0 and 1 and calculate the mean of the array
import numpy as np
from numpy import random
ra1 = np.random.rand(5,5)
print(ra1)
print(f"Mean: {ra1.mean()}")

[[0.87822398 0.01723547 0.96328283 0.16954031 0.81349307]
 [0.98386301 0.09728886 0.60611149 0.15276771 0.81101434]
 [0.61141851 0.98521829 0.96819731 0.58722265 0.29703408]
 [0.00977116 0.21704314 0.65315908 0.57198788 0.82991907]
 [0.58015781 0.12897566 0.89425463 0.71351642 0.22471522]]
Mean: 0.5506164788990834


In [2]:
# Generate a one-dimensional array with 100 random numbers and reshape it into a 5x20 matrix.
np.random.rand(100).reshape(5,20)

array([[0.57822078, 0.13527759, 0.00297718, 0.70995166, 0.55701385,
        0.27836099, 0.57816682, 0.77405876, 0.0368219 , 0.47191992,
        0.40405044, 0.66314845, 0.68985548, 0.58977383, 0.74132722,
        0.41853626, 0.66663026, 0.44592582, 0.23122306, 0.62668151],
       [0.89569863, 0.07593886, 0.01547361, 0.74470403, 0.67338094,
        0.50614858, 0.34903837, 0.35940727, 0.31149513, 0.45249334,
        0.45254376, 0.08350295, 0.16685072, 0.16653389, 0.69452249,
        0.13472852, 0.61513482, 0.7122658 , 0.85192224, 0.41438926],
       [0.18411662, 0.25689293, 0.06659029, 0.64080088, 0.51479859,
        0.99643291, 0.67316856, 0.14417728, 0.21330963, 0.65498403,
        0.31545386, 0.60660632, 0.38050917, 0.4915373 , 0.11873789,
        0.0112094 , 0.37205325, 0.94476649, 0.63091497, 0.14220029],
       [0.17245876, 0.85951627, 0.58832829, 0.05775288, 0.50982605,
        0.18100986, 0.95369187, 0.32515976, 0.85692184, 0.46432051,
        0.48391567, 0.2920804 , 0.12790106, 0

In [3]:
# Create a 4x4 array filled with zeros.
np.full((4,4), 0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
# Generate a 1-dimensional array containing even numbers from 2 to 20.
np.arange(start=2, stop=21, step=2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
# Create a 3x3 matrix where the values range from 0 to 8.
np.linspace(start=0, stop=8, num=9).reshape(3,3)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [7]:
# Calculate the sum of elements in each column of the array in question 1
print(f"Column sum: {ra1.sum(axis=0)}")

Column sum: [3.06343446 1.44576141 4.08500534 2.19503497 2.97617579]


In [8]:
# Given two vectors, calculate their dot product.
vec1 = np.array([1, 2, 3]) 
vec2 = np.array([4, 5, 6])
np.dot(vec1, vec2)

32

In [9]:
# Calculate the standard deviation of the elements of the array in question 1.
ra1.std()

0.3318834923075939

In [11]:
# Given a 2D array matrix and a 1D array vec, use broadcasting to add the elements of vec to each row of matrix.
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vec = np.array([1, 2, 3])
matrix + vec

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [12]:
# Multiply each column of the 3x3 matrix by a given vector, using broadcasting.
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vec = np.array([1, 2, 3])
matrix * vec

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])